usuario=str(input("Ingrese el nombre del primer usuario:"))
usuario1=str(input("Ingrese el nombre del segundo usuario:"))
print("Indiquen si las afirmaciones son verdaderas o falsas")
print("Turno de: ", usuario)
print("Todas las lunas tienes bordes de color rojo:")
preg=int(input("1- falso, 0-verdadero:"))
print("Turno de: ", usuario1)
print("Todas las lunas tienes bordes de color rojo:")
preg0_5=int(input("1- Falso, 0-Verdadero:"))
print("Turno de: ", usuario)
print("No todos los cuadrados estan rellenos con color:")
preg1=int(input("1- Verdadero, 0-Falso:"))
print("Turno de: ", usuario1)
print("No todos los cuadrados estan rellenos con color:")
preg1_5=int(input("1- Verdadero, 0-Falso:"))
print("Turno de: ", usuario)
print("Ningun cuadrado es de color rosado:")
preg2=int(input("1- Verdadero, 0-Falso:"))
print("Turno de: ", usuario1)
print("Ningun cuadrado es de color rosado:")
preg2_5=int(input("1- Verdadero, 0-Falso:"))
print("Turno de: ", usuario)
print("Todas las figuras rellenas de color violetas son flechas:")
preg3=int(input("1- Verdadero, 0-Falso:"))
print("Turno de: ", usuario1)
print("Todas las figuras rellenas de color violetas son flechas:")
preg3_5=int(input("1- Verdadero, 0-Falso:"))
print("Turno de: ", usuario)
print("Todas las figuras rellenas de color amarillas son rombos:")
preg4=int(input("1- Verdadero, 0-Falso:"))
print("Turno de: ", usuario1)
print("Todas las figuras rellenas de color amarillas son rombos:")
preg4_5=int(input("1- Verdadero, 0-Falso:"))
print("Turno de: ", usuario)
print("Ningun rombo esde color rojo:")
preg5=int(input("1- Verdadero, 0-Falso:"))
print("Turno de: ", usuario1)
print("Ningun rombo esde color rojo:")
preg5_5=int(input("1- Verdadero, 0-Falso:"))
puntaje=preg + preg1 + preg2 + preg3 + preg4 + preg5
puntaje2=preg0_5 + preg1_5 + preg2_5 + preg3_5 + preg4_5 + preg5_5
print("El puntaje final de ", usuario , "es: ", puntaje)
print("El puntaje final de ", usuario1 , "es: ", puntaje2)